# Generated by Django 5.0.3 on 2024-03-16 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id_personaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('verso', models.CharField(max_length=100)),
                ('escala', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('name_role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Waifu',
            fields=[
                ('id_waifu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('anime', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=50)),
                ('puntuación_total', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cant_puntuaciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('id_personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_project.personaje')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_project.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_project.role')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_project.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(through='api_project.User_Role', to='api_project.role'),
        ),
        migrations.CreateModel(
            name='Waifu_raiting',
            fields=[
                ('id_waifu_rating', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_project.user')),
                ('id_waifu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_project.waifu')),
            ],
        ),
    ]
