# Generated by Django 5.0.3 on 2024-03-16 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comentarios',
            table='Comentario',
        ),
        migrations.AlterModelTable(
            name='personaje',
            table='Personaje',
        ),
        migrations.AlterModelTable(
            name='role',
            table='Role',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
        migrations.AlterModelTable(
            name='user_role',
            table='User_Role',
        ),
        migrations.AlterModelTable(
            name='waifu',
            table='Waifu',
        ),
        migrations.AlterModelTable(
            name='waifu_raiting',
            table='Waifu_raiting',
        ),
    ]
